apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ckxs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ckxs
    app.kubernetes.io/part-of: ci1t-830-0019-app
  name: devfile-sample-ckxs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ckxs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ckxs
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0019-tenant/ci1t-830-0019-app/devfile-sample-ckxs@sha256:c6c0ce86cd5facc76eb641002430ca47993fedaad9ae2213a893fd4088b97346
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
